-- WBZ auth/profile tables
-- Run this in Supabase SQL editor.

create table if not exists public.user_profiles (
  email text primary key,
  display_name text null,
  bio text null,
  preferred_mode varchar(24) null,
  favorite_map varchar(24) null,
  main_weapon varchar(32) null,
  play_style varchar(24) null,
  accent_color varchar(16) null,
  banner_image_url text null,
  social_link text null,
  avatar_url text null,
  provider varchar(32) null,
  login_count integer not null default 0,
  last_login_at timestamptz null,
  last_logout_at timestamptz null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint user_profiles_login_count_non_negative check (login_count >= 0)
);

create index if not exists idx_user_profiles_last_login_at on public.user_profiles (last_login_at desc);
create index if not exists idx_user_profiles_provider on public.user_profiles (provider);

drop trigger if exists trg_user_profiles_set_updated_at on public.user_profiles;
create trigger trg_user_profiles_set_updated_at
before update on public.user_profiles
for each row
execute function public.set_updated_at();

create table if not exists public.auth_events (
  id bigint generated by default as identity primary key,
  email text not null,
  event_type varchar(16) not null,
  provider varchar(32) null,
  event_meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  constraint auth_events_type_check check (event_type in ('login', 'logout'))
);

create index if not exists idx_auth_events_email_created_at on public.auth_events (email, created_at desc);
create index if not exists idx_auth_events_type_created_at on public.auth_events (event_type, created_at desc);
